FROM node:20.16.0 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --only=production

COPY . .


FROM node:20.16.0-alpine AS production

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5605

CMD ["node", "server.js"]
